# C:/Users/Vlad/PycharmProjects/CW_5.Habits_tracker/nginx/nginx.conf

# Определяем "upstream" - это наше Django-приложение, работающее на Gunicorn
upstream app {
    # 'app' - это имя сервиса из docker-compose.yml, 8000 - порт, который слушает Gunicorn
    server app:8000;
}

server {
    # Nginx будет слушать на порту 80
    listen 80;

    # Обрабатываем запросы к статическим файлам
    location /static/ {
        # Указываем, где Nginx должен искать статические файлы внутри контейнера
        alias /app/static/;
    }

    # Обрабатываем запросы к медиа-файлам
    location /media/ {
        alias /app/media/;
    }

    # Все остальные запросы передаем нашему Django-приложению
    location / {
        proxy_pass http://app;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }
}